# This is a basic workflow to help you get started with Actions

name: pip3 install yq

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pip3 list
        run: pip3 list


      - name: pip3 install setuptools
        run: pip3 install setuptools

      - name: pip3 install yq
        run: pip3 install yq

      - name: show
        run: which yq
